# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-march=native -O2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
FEATURES="${FEATURES} parallel-fetch parallel-install"
ACCEPT_LICENSE="*"
PORTAGE_NICENESS=1
INPUT_DEVICES="libinput mouse keyboard joystick"

VIDEO_CARDS="amdgpu radeonsi vmware"

MAKEOPTS="-j12"
EMERGE_DEFAULT_OPTS="--jobs 12 --load-average 12.0"

USE="mtp amdgpu radeonsi gtk qt5 qt6 pipewire pulseaudio X udev bluetooth vulkan -doc -wayland -qtwebengine -systemd -webengine grub"

# NOTE: This stage was built with the bindist Use flag enabled
PORTDIR="/var/db/repos/gentoo"
DISTDIR="/var/cache/distfiles"
PKGDIR="/var/cache/binpkgs"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.utf8
GRUB_PLATFORMS="efi-64"
QEMU_USER_TARGETS="i386 x86_64"
QEMU_SOFTMMU_TARGETS="i386 x86_64"
GENTOO_MIRRORS="https://ftp.heanet.ie/mirrors/gentoo.org/ \
    http://ftp.heanet.ie/mirrors/gentoo.org/ \
    rsync://ftp.heanet.ie/mirrors/gentoo.org/ \
    https://mirror.bytemark.co.uk/gentoo/ \
    http://mirror.bytemark.co.uk/gentoo/ \
    rsync://mirror.bytemark.co.uk/gentoo/ \
    https://mirrors.gethosted.online/gentoo/ \
    http://mirrors.gethosted.online/gentoo/ \
    https://www.mirrorservice.org/sites/distfiles.gentoo.org/ \
    http://www.mirrorservice.org/sites/distfiles.gentoo.org/ \
    ftp://ftp.mirrorservice.org/sites/distfiles.gentoo.org/ \
    rsync://rsync.mirrorservice.org/distfiles.gentoo.org/"
